//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows_Colegio.ProxyCurso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Colegio")]
    [System.SerializableAttribute()]
    public partial class CursoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivocurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activocur {
            get {
                return this.ActivocurField;
            }
            set {
                if ((this.ActivocurField.Equals(value) != true)) {
                    this.ActivocurField = value;
                    this.RaisePropertyChanged("Activocur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdCurso {
            get {
                return this.IdCursoField;
            }
            set {
                if ((this.IdCursoField.Equals(value) != true)) {
                    this.IdCursoField = value;
                    this.RaisePropertyChanged("IdCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNivel {
            get {
                return this.IdNivelField;
            }
            set {
                if ((this.IdNivelField.Equals(value) != true)) {
                    this.IdNivelField = value;
                    this.RaisePropertyChanged("IdNivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCurso.IServicioCurso")]
    public interface IServicioCurso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/UpdateCurso", ReplyAction="http://tempuri.org/IServicioCurso/UpdateCursoResponse")]
        bool UpdateCurso(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/UpdateCurso", ReplyAction="http://tempuri.org/IServicioCurso/UpdateCursoResponse")]
        System.Threading.Tasks.Task<bool> UpdateCursoAsync(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/DeleteCurso", ReplyAction="http://tempuri.org/IServicioCurso/DeleteCursoResponse")]
        bool DeleteCurso(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/DeleteCurso", ReplyAction="http://tempuri.org/IServicioCurso/DeleteCursoResponse")]
        System.Threading.Tasks.Task<bool> DeleteCursoAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetCurso", ReplyAction="http://tempuri.org/IServicioCurso/GetCursoResponse")]
        AppWindows_Colegio.ProxyCurso.CursoBE GetCurso(int strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetCurso", ReplyAction="http://tempuri.org/IServicioCurso/GetCursoResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE> GetCursoAsync(int strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetCursos", ReplyAction="http://tempuri.org/IServicioCurso/GetCursosResponse")]
        AppWindows_Colegio.ProxyCurso.CursoBE[] GetCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetCursos", ReplyAction="http://tempuri.org/IServicioCurso/GetCursosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE[]> GetCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetNiveles", ReplyAction="http://tempuri.org/IServicioCurso/GetNivelesResponse")]
        AppWindows_Colegio.ProxyCurso.CursoBE[] GetNiveles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetNiveles", ReplyAction="http://tempuri.org/IServicioCurso/GetNivelesResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE[]> GetNivelesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/RegistrarCurso", ReplyAction="http://tempuri.org/IServicioCurso/RegistrarCursoResponse")]
        bool RegistrarCurso(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/RegistrarCurso", ReplyAction="http://tempuri.org/IServicioCurso/RegistrarCursoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarCursoAsync(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/DetalleCursoNivel", ReplyAction="http://tempuri.org/IServicioCurso/DetalleCursoNivelResponse")]
        AppWindows_Colegio.ProxyCurso.CursoBE DetalleCursoNivel(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/DetalleCursoNivel", ReplyAction="http://tempuri.org/IServicioCurso/DetalleCursoNivelResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE> DetalleCursoNivelAsync(short strId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCursoChannel : AppWindows_Colegio.ProxyCurso.IServicioCurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursoClient : System.ServiceModel.ClientBase<AppWindows_Colegio.ProxyCurso.IServicioCurso>, AppWindows_Colegio.ProxyCurso.IServicioCurso {
        
        public ServicioCursoClient() {
        }
        
        public ServicioCursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateCurso(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE) {
            return base.Channel.UpdateCurso(objCursoBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCursoAsync(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE) {
            return base.Channel.UpdateCursoAsync(objCursoBE);
        }
        
        public bool DeleteCurso(short strId) {
            return base.Channel.DeleteCurso(strId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCursoAsync(short strId) {
            return base.Channel.DeleteCursoAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyCurso.CursoBE GetCurso(int strId) {
            return base.Channel.GetCurso(strId);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE> GetCursoAsync(int strId) {
            return base.Channel.GetCursoAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyCurso.CursoBE[] GetCursos() {
            return base.Channel.GetCursos();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE[]> GetCursosAsync() {
            return base.Channel.GetCursosAsync();
        }
        
        public AppWindows_Colegio.ProxyCurso.CursoBE[] GetNiveles() {
            return base.Channel.GetNiveles();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE[]> GetNivelesAsync() {
            return base.Channel.GetNivelesAsync();
        }
        
        public bool RegistrarCurso(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE) {
            return base.Channel.RegistrarCurso(objCursoBE);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarCursoAsync(AppWindows_Colegio.ProxyCurso.CursoBE objCursoBE) {
            return base.Channel.RegistrarCursoAsync(objCursoBE);
        }
        
        public AppWindows_Colegio.ProxyCurso.CursoBE DetalleCursoNivel(short strId) {
            return base.Channel.DetalleCursoNivel(strId);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyCurso.CursoBE> DetalleCursoNivelAsync(short strId) {
            return base.Channel.DetalleCursoNivelAsync(strId);
        }
    }
}
