//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows_Colegio.ProxyExtra {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Colegio")]
    [System.SerializableAttribute()]
    public partial class AlumnoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Mvaract_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarape_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarcod_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardir_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardocide_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Mvarfecnac_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Mvarfecres_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvarfinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarid_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvaridcursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarnom_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarnom_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvarnotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MvarpromedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MvarretroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarsex_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarvalorcod_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_ult_modField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_ult_mod {
            get {
                return this.Fecha_ult_modField;
            }
            set {
                if ((this.Fecha_ult_modField.Equals(value) != true)) {
                    this.Fecha_ult_modField = value;
                    this.RaisePropertyChanged("Fecha_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mvaract_al {
            get {
                return this.Mvaract_alField;
            }
            set {
                if ((this.Mvaract_alField.Equals(value) != true)) {
                    this.Mvaract_alField = value;
                    this.RaisePropertyChanged("Mvaract_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarape_al {
            get {
                return this.Mvarape_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarape_alField, value) != true)) {
                    this.Mvarape_alField = value;
                    this.RaisePropertyChanged("Mvarape_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarcod_al {
            get {
                return this.Mvarcod_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarcod_alField, value) != true)) {
                    this.Mvarcod_alField = value;
                    this.RaisePropertyChanged("Mvarcod_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardir_al {
            get {
                return this.Mvardir_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardir_alField, value) != true)) {
                    this.Mvardir_alField = value;
                    this.RaisePropertyChanged("Mvardir_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardocide_al {
            get {
                return this.Mvardocide_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardocide_alField, value) != true)) {
                    this.Mvardocide_alField = value;
                    this.RaisePropertyChanged("Mvardocide_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mvarfecnac_al {
            get {
                return this.Mvarfecnac_alField;
            }
            set {
                if ((this.Mvarfecnac_alField.Equals(value) != true)) {
                    this.Mvarfecnac_alField = value;
                    this.RaisePropertyChanged("Mvarfecnac_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mvarfecres_al {
            get {
                return this.Mvarfecres_alField;
            }
            set {
                if ((this.Mvarfecres_alField.Equals(value) != true)) {
                    this.Mvarfecres_alField = value;
                    this.RaisePropertyChanged("Mvarfecres_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarfinal {
            get {
                return this.MvarfinalField;
            }
            set {
                if ((this.MvarfinalField.Equals(value) != true)) {
                    this.MvarfinalField = value;
                    this.RaisePropertyChanged("Mvarfinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_alumno {
            get {
                return this.Mvarid_alumnoField;
            }
            set {
                if ((this.Mvarid_alumnoField.Equals(value) != true)) {
                    this.Mvarid_alumnoField = value;
                    this.RaisePropertyChanged("Mvarid_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarid_curso {
            get {
                return this.Mvarid_cursoField;
            }
            set {
                if ((this.Mvarid_cursoField.Equals(value) != true)) {
                    this.Mvarid_cursoField = value;
                    this.RaisePropertyChanged("Mvarid_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_distrito {
            get {
                return this.Mvarid_distritoField;
            }
            set {
                if ((this.Mvarid_distritoField.Equals(value) != true)) {
                    this.Mvarid_distritoField = value;
                    this.RaisePropertyChanged("Mvarid_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvaridcurso {
            get {
                return this.MvaridcursoField;
            }
            set {
                if ((this.MvaridcursoField.Equals(value) != true)) {
                    this.MvaridcursoField = value;
                    this.RaisePropertyChanged("Mvaridcurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarnom_al {
            get {
                return this.Mvarnom_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarnom_alField, value) != true)) {
                    this.Mvarnom_alField = value;
                    this.RaisePropertyChanged("Mvarnom_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarnom_distrito {
            get {
                return this.Mvarnom_distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarnom_distritoField, value) != true)) {
                    this.Mvarnom_distritoField = value;
                    this.RaisePropertyChanged("Mvarnom_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota {
            get {
                return this.MvarnotaField;
            }
            set {
                if ((this.MvarnotaField.Equals(value) != true)) {
                    this.MvarnotaField = value;
                    this.RaisePropertyChanged("Mvarnota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota1 {
            get {
                return this.Mvarnota1Field;
            }
            set {
                if ((this.Mvarnota1Field.Equals(value) != true)) {
                    this.Mvarnota1Field = value;
                    this.RaisePropertyChanged("Mvarnota1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota2 {
            get {
                return this.Mvarnota2Field;
            }
            set {
                if ((this.Mvarnota2Field.Equals(value) != true)) {
                    this.Mvarnota2Field = value;
                    this.RaisePropertyChanged("Mvarnota2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota3 {
            get {
                return this.Mvarnota3Field;
            }
            set {
                if ((this.Mvarnota3Field.Equals(value) != true)) {
                    this.Mvarnota3Field = value;
                    this.RaisePropertyChanged("Mvarnota3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mvarpromedio {
            get {
                return this.MvarpromedioField;
            }
            set {
                if ((this.MvarpromedioField.Equals(value) != true)) {
                    this.MvarpromedioField = value;
                    this.RaisePropertyChanged("Mvarpromedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarretro {
            get {
                return this.MvarretroField;
            }
            set {
                if ((object.ReferenceEquals(this.MvarretroField, value) != true)) {
                    this.MvarretroField = value;
                    this.RaisePropertyChanged("Mvarretro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarsex_al {
            get {
                return this.Mvarsex_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarsex_alField, value) != true)) {
                    this.Mvarsex_alField = value;
                    this.RaisePropertyChanged("Mvarsex_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarvalorcod_al {
            get {
                return this.Mvarvalorcod_alField;
            }
            set {
                if ((this.Mvarvalorcod_alField.Equals(value) != true)) {
                    this.Mvarvalorcod_alField = value;
                    this.RaisePropertyChanged("Mvarvalorcod_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_ult_mod {
            get {
                return this.Usu_ult_modField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_ult_modField, value) != true)) {
                    this.Usu_ult_modField = value;
                    this.RaisePropertyChanged("Usu_ult_mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistritoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Colegio")]
    [System.SerializableAttribute()]
    public partial class DistritoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MvarDes_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvarId_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MvarNombre_distritroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MvarDes_distrito {
            get {
                return this.MvarDes_distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.MvarDes_distritoField, value) != true)) {
                    this.MvarDes_distritoField = value;
                    this.RaisePropertyChanged("MvarDes_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MvarId_distrito {
            get {
                return this.MvarId_distritoField;
            }
            set {
                if ((this.MvarId_distritoField.Equals(value) != true)) {
                    this.MvarId_distritoField = value;
                    this.RaisePropertyChanged("MvarId_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MvarNombre_distritro {
            get {
                return this.MvarNombre_distritroField;
            }
            set {
                if ((object.ReferenceEquals(this.MvarNombre_distritroField, value) != true)) {
                    this.MvarNombre_distritroField = value;
                    this.RaisePropertyChanged("MvarNombre_distritro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyExtra.IIServicioExtra")]
    public interface IIServicioExtra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/AsignarCursoDocente", ReplyAction="http://tempuri.org/IIServicioExtra/AsignarCursoDocenteResponse")]
        bool AsignarCursoDocente(int idCurso, int idDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/AsignarCursoDocente", ReplyAction="http://tempuri.org/IIServicioExtra/AsignarCursoDocenteResponse")]
        System.Threading.Tasks.Task<bool> AsignarCursoDocenteAsync(int idCurso, int idDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/GetTopAlumnos", ReplyAction="http://tempuri.org/IIServicioExtra/GetTopAlumnosResponse")]
        AppWindows_Colegio.ProxyExtra.AlumnoBE[] GetTopAlumnos(int maximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/GetTopAlumnos", ReplyAction="http://tempuri.org/IIServicioExtra/GetTopAlumnosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.AlumnoBE[]> GetTopAlumnosAsync(int maximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/AsignarImagenCurso", ReplyAction="http://tempuri.org/IIServicioExtra/AsignarImagenCursoResponse")]
        bool AsignarImagenCurso(byte[] imagen, int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/AsignarImagenCurso", ReplyAction="http://tempuri.org/IIServicioExtra/AsignarImagenCursoResponse")]
        System.Threading.Tasks.Task<bool> AsignarImagenCursoAsync(byte[] imagen, int idCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/GetAlumnosDeudores", ReplyAction="http://tempuri.org/IIServicioExtra/GetAlumnosDeudoresResponse")]
        AppWindows_Colegio.ProxyExtra.AlumnoBE[] GetAlumnosDeudores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/GetAlumnosDeudores", ReplyAction="http://tempuri.org/IIServicioExtra/GetAlumnosDeudoresResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.AlumnoBE[]> GetAlumnosDeudoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/LoginUsuario", ReplyAction="http://tempuri.org/IIServicioExtra/LoginUsuarioResponse")]
        bool LoginUsuario(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/LoginUsuario", ReplyAction="http://tempuri.org/IIServicioExtra/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<bool> LoginUsuarioAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/ListarDistritos", ReplyAction="http://tempuri.org/IIServicioExtra/ListarDistritosResponse")]
        AppWindows_Colegio.ProxyExtra.DistritoBE[] ListarDistritos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioExtra/ListarDistritos", ReplyAction="http://tempuri.org/IIServicioExtra/ListarDistritosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.DistritoBE[]> ListarDistritosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIServicioExtraChannel : AppWindows_Colegio.ProxyExtra.IIServicioExtra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IServicioExtraClient : System.ServiceModel.ClientBase<AppWindows_Colegio.ProxyExtra.IIServicioExtra>, AppWindows_Colegio.ProxyExtra.IIServicioExtra {
        
        public IServicioExtraClient() {
        }
        
        public IServicioExtraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IServicioExtraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioExtraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioExtraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AsignarCursoDocente(int idCurso, int idDocente) {
            return base.Channel.AsignarCursoDocente(idCurso, idDocente);
        }
        
        public System.Threading.Tasks.Task<bool> AsignarCursoDocenteAsync(int idCurso, int idDocente) {
            return base.Channel.AsignarCursoDocenteAsync(idCurso, idDocente);
        }
        
        public AppWindows_Colegio.ProxyExtra.AlumnoBE[] GetTopAlumnos(int maximo) {
            return base.Channel.GetTopAlumnos(maximo);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.AlumnoBE[]> GetTopAlumnosAsync(int maximo) {
            return base.Channel.GetTopAlumnosAsync(maximo);
        }
        
        public bool AsignarImagenCurso(byte[] imagen, int idCurso) {
            return base.Channel.AsignarImagenCurso(imagen, idCurso);
        }
        
        public System.Threading.Tasks.Task<bool> AsignarImagenCursoAsync(byte[] imagen, int idCurso) {
            return base.Channel.AsignarImagenCursoAsync(imagen, idCurso);
        }
        
        public AppWindows_Colegio.ProxyExtra.AlumnoBE[] GetAlumnosDeudores() {
            return base.Channel.GetAlumnosDeudores();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.AlumnoBE[]> GetAlumnosDeudoresAsync() {
            return base.Channel.GetAlumnosDeudoresAsync();
        }
        
        public bool LoginUsuario(string usuario, string clave) {
            return base.Channel.LoginUsuario(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<bool> LoginUsuarioAsync(string usuario, string clave) {
            return base.Channel.LoginUsuarioAsync(usuario, clave);
        }
        
        public AppWindows_Colegio.ProxyExtra.DistritoBE[] ListarDistritos() {
            return base.Channel.ListarDistritos();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyExtra.DistritoBE[]> ListarDistritosAsync() {
            return base.Channel.ListarDistritosAsync();
        }
    }
}
