//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows_Colegio.ProxyAlumno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Colegio")]
    [System.SerializableAttribute()]
    public partial class AlumnoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Mvaract_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarape_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarcod_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardes_periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardir_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardocide_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Mvarfecnac_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Mvarfecres_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvarfinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarid_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarid_periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvaridcursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarnom_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarnom_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MvarnotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mvarnota3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MvarpromedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MvarretroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarsex_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarvalorcod_alField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_ult_modField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_ult_mod {
            get {
                return this.Fecha_ult_modField;
            }
            set {
                if ((this.Fecha_ult_modField.Equals(value) != true)) {
                    this.Fecha_ult_modField = value;
                    this.RaisePropertyChanged("Fecha_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mvaract_al {
            get {
                return this.Mvaract_alField;
            }
            set {
                if ((this.Mvaract_alField.Equals(value) != true)) {
                    this.Mvaract_alField = value;
                    this.RaisePropertyChanged("Mvaract_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarape_al {
            get {
                return this.Mvarape_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarape_alField, value) != true)) {
                    this.Mvarape_alField = value;
                    this.RaisePropertyChanged("Mvarape_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarcod_al {
            get {
                return this.Mvarcod_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarcod_alField, value) != true)) {
                    this.Mvarcod_alField = value;
                    this.RaisePropertyChanged("Mvarcod_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardes_periodo {
            get {
                return this.Mvardes_periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardes_periodoField, value) != true)) {
                    this.Mvardes_periodoField = value;
                    this.RaisePropertyChanged("Mvardes_periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardir_al {
            get {
                return this.Mvardir_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardir_alField, value) != true)) {
                    this.Mvardir_alField = value;
                    this.RaisePropertyChanged("Mvardir_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardocide_al {
            get {
                return this.Mvardocide_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardocide_alField, value) != true)) {
                    this.Mvardocide_alField = value;
                    this.RaisePropertyChanged("Mvardocide_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mvarfecnac_al {
            get {
                return this.Mvarfecnac_alField;
            }
            set {
                if ((this.Mvarfecnac_alField.Equals(value) != true)) {
                    this.Mvarfecnac_alField = value;
                    this.RaisePropertyChanged("Mvarfecnac_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mvarfecres_al {
            get {
                return this.Mvarfecres_alField;
            }
            set {
                if ((this.Mvarfecres_alField.Equals(value) != true)) {
                    this.Mvarfecres_alField = value;
                    this.RaisePropertyChanged("Mvarfecres_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarfinal {
            get {
                return this.MvarfinalField;
            }
            set {
                if ((this.MvarfinalField.Equals(value) != true)) {
                    this.MvarfinalField = value;
                    this.RaisePropertyChanged("Mvarfinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_alumno {
            get {
                return this.Mvarid_alumnoField;
            }
            set {
                if ((this.Mvarid_alumnoField.Equals(value) != true)) {
                    this.Mvarid_alumnoField = value;
                    this.RaisePropertyChanged("Mvarid_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarid_curso {
            get {
                return this.Mvarid_cursoField;
            }
            set {
                if ((this.Mvarid_cursoField.Equals(value) != true)) {
                    this.Mvarid_cursoField = value;
                    this.RaisePropertyChanged("Mvarid_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_distrito {
            get {
                return this.Mvarid_distritoField;
            }
            set {
                if ((this.Mvarid_distritoField.Equals(value) != true)) {
                    this.Mvarid_distritoField = value;
                    this.RaisePropertyChanged("Mvarid_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarid_periodo {
            get {
                return this.Mvarid_periodoField;
            }
            set {
                if ((this.Mvarid_periodoField.Equals(value) != true)) {
                    this.Mvarid_periodoField = value;
                    this.RaisePropertyChanged("Mvarid_periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvaridcurso {
            get {
                return this.MvaridcursoField;
            }
            set {
                if ((this.MvaridcursoField.Equals(value) != true)) {
                    this.MvaridcursoField = value;
                    this.RaisePropertyChanged("Mvaridcurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarnom_al {
            get {
                return this.Mvarnom_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarnom_alField, value) != true)) {
                    this.Mvarnom_alField = value;
                    this.RaisePropertyChanged("Mvarnom_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarnom_distrito {
            get {
                return this.Mvarnom_distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarnom_distritoField, value) != true)) {
                    this.Mvarnom_distritoField = value;
                    this.RaisePropertyChanged("Mvarnom_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota {
            get {
                return this.MvarnotaField;
            }
            set {
                if ((this.MvarnotaField.Equals(value) != true)) {
                    this.MvarnotaField = value;
                    this.RaisePropertyChanged("Mvarnota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota1 {
            get {
                return this.Mvarnota1Field;
            }
            set {
                if ((this.Mvarnota1Field.Equals(value) != true)) {
                    this.Mvarnota1Field = value;
                    this.RaisePropertyChanged("Mvarnota1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota2 {
            get {
                return this.Mvarnota2Field;
            }
            set {
                if ((this.Mvarnota2Field.Equals(value) != true)) {
                    this.Mvarnota2Field = value;
                    this.RaisePropertyChanged("Mvarnota2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mvarnota3 {
            get {
                return this.Mvarnota3Field;
            }
            set {
                if ((this.Mvarnota3Field.Equals(value) != true)) {
                    this.Mvarnota3Field = value;
                    this.RaisePropertyChanged("Mvarnota3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mvarpromedio {
            get {
                return this.MvarpromedioField;
            }
            set {
                if ((this.MvarpromedioField.Equals(value) != true)) {
                    this.MvarpromedioField = value;
                    this.RaisePropertyChanged("Mvarpromedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarretro {
            get {
                return this.MvarretroField;
            }
            set {
                if ((object.ReferenceEquals(this.MvarretroField, value) != true)) {
                    this.MvarretroField = value;
                    this.RaisePropertyChanged("Mvarretro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarsex_al {
            get {
                return this.Mvarsex_alField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarsex_alField, value) != true)) {
                    this.Mvarsex_alField = value;
                    this.RaisePropertyChanged("Mvarsex_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarvalorcod_al {
            get {
                return this.Mvarvalorcod_alField;
            }
            set {
                if ((this.Mvarvalorcod_alField.Equals(value) != true)) {
                    this.Mvarvalorcod_alField = value;
                    this.RaisePropertyChanged("Mvarvalorcod_al");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_ult_mod {
            get {
                return this.Usu_ult_modField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_ult_modField, value) != true)) {
                    this.Usu_ult_modField = value;
                    this.RaisePropertyChanged("Usu_ult_mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAlumno.IServicioAlumno")]
    public interface IServicioAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/RegistrarNotas", ReplyAction="http://tempuri.org/IServicioAlumno/RegistrarNotasResponse")]
        bool RegistrarNotas(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/RegistrarNotas", ReplyAction="http://tempuri.org/IServicioAlumno/RegistrarNotasResponse")]
        System.Threading.Tasks.Task<bool> RegistrarNotasAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertAlumnoResponse")]
        bool InsertAlumno(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertAlumnoResponse")]
        System.Threading.Tasks.Task<bool> InsertAlumnoAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/UpdateAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/UpdateAlumnoResponse")]
        bool UpdateAlumno(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/UpdateAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/UpdateAlumnoResponse")]
        System.Threading.Tasks.Task<bool> UpdateAlumnoAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/DeleteAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/DeleteAlumnoResponse")]
        bool DeleteAlumno(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/DeleteAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/DeleteAlumnoResponse")]
        System.Threading.Tasks.Task<bool> DeleteAlumnoAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAllAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/GetAllAlumnosResponse")]
        AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetAllAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAllAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/GetAllAlumnosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetAllAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAlumnoResponse")]
        AppWindows_Colegio.ProxyAlumno.AlumnoBE GetAlumno(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAlumnoResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE> GetAlumnoAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/BuscarAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/BuscarAlumnosResponse")]
        AppWindows_Colegio.ProxyAlumno.AlumnoBE[] BuscarAlumnos(string ape);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/BuscarAlumnos", ReplyAction="http://tempuri.org/IServicioAlumno/BuscarAlumnosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> BuscarAlumnosAsync(string ape);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetNotas", ReplyAction="http://tempuri.org/IServicioAlumno/GetNotasResponse")]
        AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetNotas(int idCur, int idAlum, int idPer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetNotas", ReplyAction="http://tempuri.org/IServicioAlumno/GetNotasResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetNotasAsync(int idCur, int idAlum, int idPer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetPeriodos", ReplyAction="http://tempuri.org/IServicioAlumno/GetPeriodosResponse")]
        AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetPeriodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetPeriodos", ReplyAction="http://tempuri.org/IServicioAlumno/GetPeriodosResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetPeriodosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAlumnoChannel : AppWindows_Colegio.ProxyAlumno.IServicioAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAlumnoClient : System.ServiceModel.ClientBase<AppWindows_Colegio.ProxyAlumno.IServicioAlumno>, AppWindows_Colegio.ProxyAlumno.IServicioAlumno {
        
        public ServicioAlumnoClient() {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarNotas(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.RegistrarNotas(objAlumnoBE);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarNotasAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.RegistrarNotasAsync(objAlumnoBE);
        }
        
        public bool InsertAlumno(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.InsertAlumno(objAlumnoBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAlumnoAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.InsertAlumnoAsync(objAlumnoBE);
        }
        
        public bool UpdateAlumno(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.UpdateAlumno(objAlumnoBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAlumnoAsync(AppWindows_Colegio.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.UpdateAlumnoAsync(objAlumnoBE);
        }
        
        public bool DeleteAlumno(short strId) {
            return base.Channel.DeleteAlumno(strId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAlumnoAsync(short strId) {
            return base.Channel.DeleteAlumnoAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetAllAlumnos() {
            return base.Channel.GetAllAlumnos();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetAllAlumnosAsync() {
            return base.Channel.GetAllAlumnosAsync();
        }
        
        public AppWindows_Colegio.ProxyAlumno.AlumnoBE GetAlumno(short strId) {
            return base.Channel.GetAlumno(strId);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE> GetAlumnoAsync(short strId) {
            return base.Channel.GetAlumnoAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyAlumno.AlumnoBE[] BuscarAlumnos(string ape) {
            return base.Channel.BuscarAlumnos(ape);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> BuscarAlumnosAsync(string ape) {
            return base.Channel.BuscarAlumnosAsync(ape);
        }
        
        public AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetNotas(int idCur, int idAlum, int idPer) {
            return base.Channel.GetNotas(idCur, idAlum, idPer);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetNotasAsync(int idCur, int idAlum, int idPer) {
            return base.Channel.GetNotasAsync(idCur, idAlum, idPer);
        }
        
        public AppWindows_Colegio.ProxyAlumno.AlumnoBE[] GetPeriodos() {
            return base.Channel.GetPeriodos();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyAlumno.AlumnoBE[]> GetPeriodosAsync() {
            return base.Channel.GetPeriodosAsync();
        }
    }
}
