//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows_Colegio.ProxyUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Colegio")]
    [System.SerializableAttribute()]
    public partial class UsuarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarape_usField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvardes_referenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Mvarfecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_referenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Mvarid_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarlog_claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarlog_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mvarnom_usField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarape_us {
            get {
                return this.Mvarape_usField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarape_usField, value) != true)) {
                    this.Mvarape_usField = value;
                    this.RaisePropertyChanged("Mvarape_us");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvardes_referencia {
            get {
                return this.Mvardes_referenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvardes_referenciaField, value) != true)) {
                    this.Mvardes_referenciaField = value;
                    this.RaisePropertyChanged("Mvardes_referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Mvarfecha_registro {
            get {
                return this.Mvarfecha_registroField;
            }
            set {
                if ((this.Mvarfecha_registroField.Equals(value) != true)) {
                    this.Mvarfecha_registroField = value;
                    this.RaisePropertyChanged("Mvarfecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_referencia {
            get {
                return this.Mvarid_referenciaField;
            }
            set {
                if ((this.Mvarid_referenciaField.Equals(value) != true)) {
                    this.Mvarid_referenciaField = value;
                    this.RaisePropertyChanged("Mvarid_referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_rol {
            get {
                return this.Mvarid_rolField;
            }
            set {
                if ((this.Mvarid_rolField.Equals(value) != true)) {
                    this.Mvarid_rolField = value;
                    this.RaisePropertyChanged("Mvarid_rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Mvarid_usuario {
            get {
                return this.Mvarid_usuarioField;
            }
            set {
                if ((this.Mvarid_usuarioField.Equals(value) != true)) {
                    this.Mvarid_usuarioField = value;
                    this.RaisePropertyChanged("Mvarid_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarlog_clave {
            get {
                return this.Mvarlog_claveField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarlog_claveField, value) != true)) {
                    this.Mvarlog_claveField = value;
                    this.RaisePropertyChanged("Mvarlog_clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarlog_usuario {
            get {
                return this.Mvarlog_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarlog_usuarioField, value) != true)) {
                    this.Mvarlog_usuarioField = value;
                    this.RaisePropertyChanged("Mvarlog_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mvarnom_us {
            get {
                return this.Mvarnom_usField;
            }
            set {
                if ((object.ReferenceEquals(this.Mvarnom_usField, value) != true)) {
                    this.Mvarnom_usField = value;
                    this.RaisePropertyChanged("Mvarnom_us");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/InsertUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/InsertUsuarioResponse")]
        bool InsertUsuario(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/InsertUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/InsertUsuarioResponse")]
        System.Threading.Tasks.Task<bool> InsertUsuarioAsync(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/UpdateUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateUsuarioResponse")]
        bool UpdateUsuario(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/UpdateUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<bool> UpdateUsuarioAsync(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/DeleteUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/DeleteUsuarioResponse")]
        bool DeleteUsuario(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/DeleteUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task<bool> DeleteUsuarioAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsuarioResponse")]
        AppWindows_Colegio.ProxyUsuario.UsuarioBE[] GetAllUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsuarioResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE[]> GetAllUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/GetUsuarioResponse")]
        AppWindows_Colegio.ProxyUsuario.UsuarioBE GetUsuario(int strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/GetUsuarioResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE> GetUsuarioAsync(int strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetRol", ReplyAction="http://tempuri.org/IServicioUsuario/GetRolResponse")]
        AppWindows_Colegio.ProxyUsuario.UsuarioBE GetRol(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetRol", ReplyAction="http://tempuri.org/IServicioUsuario/GetRolResponse")]
        System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE> GetRolAsync(string usuario, string clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : AppWindows_Colegio.ProxyUsuario.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<AppWindows_Colegio.ProxyUsuario.IServicioUsuario>, AppWindows_Colegio.ProxyUsuario.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertUsuario(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.InsertUsuario(objUsuarioBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUsuarioAsync(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.InsertUsuarioAsync(objUsuarioBE);
        }
        
        public bool UpdateUsuario(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.UpdateUsuario(objUsuarioBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUsuarioAsync(AppWindows_Colegio.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.UpdateUsuarioAsync(objUsuarioBE);
        }
        
        public bool DeleteUsuario(short strId) {
            return base.Channel.DeleteUsuario(strId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUsuarioAsync(short strId) {
            return base.Channel.DeleteUsuarioAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyUsuario.UsuarioBE[] GetAllUsuario() {
            return base.Channel.GetAllUsuario();
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE[]> GetAllUsuarioAsync() {
            return base.Channel.GetAllUsuarioAsync();
        }
        
        public AppWindows_Colegio.ProxyUsuario.UsuarioBE GetUsuario(int strId) {
            return base.Channel.GetUsuario(strId);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE> GetUsuarioAsync(int strId) {
            return base.Channel.GetUsuarioAsync(strId);
        }
        
        public AppWindows_Colegio.ProxyUsuario.UsuarioBE GetRol(string usuario, string clave) {
            return base.Channel.GetRol(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<AppWindows_Colegio.ProxyUsuario.UsuarioBE> GetRolAsync(string usuario, string clave) {
            return base.Channel.GetRolAsync(usuario, clave);
        }
    }
}
