
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class DOCENTE
{

    public int IdDocente { get; set; }

    public Nullable<int> ValorCodigo { get; set; }

    public string Codigo { get; set; }

    public string DocumentoIdentidad { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public Nullable<System.DateTime> FechaNacimiento { get; set; }

    public string Sexo { get; set; }

    public string GradoEstudio { get; set; }

    public string Direccion { get; set; }

    public string Email { get; set; }

    public string NumeroTelefono { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }

    public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }

    public string Usu_Ult_Mod { get; set; }

    public Nullable<int> IdCurso { get; set; }

    public Nullable<int> idDistrito { get; set; }



    public virtual Distrito Distrito { get; set; }

    public virtual CURSO CURSO { get; set; }

}

}
