
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Colegio
{

using System;
    using System.Collections.Generic;
    
public partial class Notas
{

    public int IDNota { get; set; }

    public int Nota1 { get; set; }

    public int Nota2 { get; set; }

    public int Nota3 { get; set; }

    public int Final { get; set; }

    public string Retroalimentacion { get; set; }

    public int IdAlumno { get; set; }

    public int IdCurso { get; set; }

    public Nullable<System.DateTime> FechaRegistro { get; set; }

    public string Usu_Docente { get; set; }

    public int IDPeriodo { get; set; }



    public virtual ALUMNO ALUMNO { get; set; }

    public virtual PERIODO PERIODO { get; set; }

    public virtual CURSO CURSO { get; set; }

}

}
